import Navbar from '@/components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import "react-quill/dist/quill.snow.css";
import ThemeProvider from '@/providers/ThemeProvider'
import { ThemeContextProvider } from '@/context/ThemeContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeContextProvider>
          <ThemeProvider>
            <div className="container_wrapper px-4 lg:px-20">
              {/* <Navbar /> */}
              {children}
              {/* <Footer /> */}
            </div>
          </ThemeProvider>
        </ThemeContextProvider>
      </body>
    </html>
  )
}
